# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa64965933385fe01def3bf6555531be12c139f786d905d80e99e8950dc7a8ca62f9789e498399cc5d5110f03966c53b04d5ca1520cbd6f494a32ce72a780fcc

test:
  secret_key_base: e503799cde3a2fd6cb55cff8eebdfea7d0fd746fbdd0c4d0ee023f67b36fd16472b3501b07ed698af14a5865e3b491d4a80405fcd9738c103d7e509cf9927a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
